feat: add hebrew locale support
abichinger/vue-js-cron pull request #60
Opened 2024-06-25 23:30 UTC by a5r0n

2024-06-27 08:15 UTC, abichinger requested changes
Thank you for your contribution!

Why is the order of the fields different?
![image](https://github.com/abichinger/vue-js-cron/assets/8122139/c526c694-64f0-4037-b34e-15caca9c9e75)

Please make sure to follow the [contribution guidlines](https://github.com/abichinger/vue-js-cron?tab=readme-ov-file#contributing)

2024-06-27 08:15 UTC, abichinger commented on core/src/locale/he.ts
> +      empty: { text: 'בכל {{field.id}}' },
`{{field.id}}` should only be used in the english translation.
![image](https://github.com/abichinger/vue-js-cron/assets/8122139/569b2361-0598-4287-8c96-ed1c63d77397)

For example, to translate `every month` you can set:
```ts
{
  '*': {
    month: {
      empty: { text: 'your translation' }
    }
  }
}
```

2024-06-27 10:15 UTC, a5r0n commented
Maybe it is an RTL issue, I tried to build and run the demo app, but no success 😕

2024-06-27 12:49 UTC, a5r0n commented
@abichinger about the RTL issue, if you can point me with direction how to add rtl support  i will be happy to implemnt this in another PR

2024-06-29 14:46 UTC, abichinger commented
@a5r0n I have no experience with RTL, so I don't know where to start 🤔

2024-06-29 17:49 UTC, a5r0n commented
All we need is to add `dir="RTL"`.
I will try to implement something, should I open new PR for this?

2024-06-29 21:41 UTC, abichinger commented
I think no changes are necessary. I just tried to set `dir="rtl"` on the `cron-light` component and it seems to work.
```html
<cron-light
      v-model="value"
      v-model:period="period"
      format="quartz"
      locale="he"
      @error="error = $event"
      dir="rtl"
    >
    </cron-light>
```
Result:
![image](https://github.com/abichinger/vue-js-cron/assets/8122139/154af9b2-1e16-4512-b11b-574d223ae9a4)

Is this as it should be?

2024-06-29 21:47 UTC, abichinger approved these changes

2024-06-29 21:58 UTC, a5r0n commented
Yes, this is great.
I was thinking maybe we should add this as a per language settings, but maybe it's out of the scope

2024-06-30 10:04 UTC, abichinger commented
> I was thinking maybe we should add this as a per language settings, but maybe it's out of the scope
I think this is out of scope, because of what I have read so far, the `dir` attribute is usually set on the `html` tag.

2024-06-30 10:04 UTC, merged

2024-06-30 10:05 UTC, abichinger commented
Thanks again!

2024-06-30 10:08 UTC, abichinger commented
:tada: This PR is included in version 3.0.5 :tada:

The release is available on [npm package (@latest dist-tag)](https://www.npmjs.com/package/@vue-js-cron/quasar/v/3.0.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-06-30 10:08 UTC, abichinger commented
:tada: This PR is included in version 3.0.5 :tada:

The release is available on [npm package (@latest dist-tag)](https://www.npmjs.com/package/@vue-js-cron/ant/v/3.0.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-06-30 10:08 UTC, abichinger commented
:tada: This PR is included in version 5.2.0 :tada:

The release is available on [npm package (@latest dist-tag)](https://www.npmjs.com/package/@vue-js-cron/core/v/5.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-06-30 10:08 UTC, abichinger commented
:tada: This PR is included in version 3.1.2 :tada:

The release is available on [npm package (@latest dist-tag)](https://www.npmjs.com/package/@vue-js-cron/element-plus/v/3.1.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-06-30 10:08 UTC, abichinger commented
:tada: This PR is included in version 4.0.5 :tada:

The release is available on [npm package (@latest dist-tag)](https://www.npmjs.com/package/@vue-js-cron/light/v/4.0.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-06-30 10:08 UTC, abichinger commented
:tada: This PR is included in version 2.0.5 :tada:

The release is available on [npm package (@latest dist-tag)](https://www.npmjs.com/package/@vue-js-cron/naive-ui/v/2.0.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-06-30 10:08 UTC, abichinger commented
:tada: This PR is included in version 5.0.5 :tada:

The release is available on [npm package (@latest dist-tag)](https://www.npmjs.com/package/@vue-js-cron/vuetify/v/5.0.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: